# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_generico', models.CharField(max_length=50)),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('forma_farmaceutica', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=100)),
                ('estado_autorizacao', models.CharField(choices=[('A', 'Autorizado'), ('NA', 'Nao autorizado')], max_length=2)),
                ('generico', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], max_length=1)),
                ('titular_AM', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('ORT', 'Ortopedia'), ('CGE', 'Clinica Geral'), ('OFT', 'Oftalmologia'), ('GNC', 'Ginecologia')], max_length=3)),
                ('cedula', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('data_da_receita', models.DateField(default=django.utils.timezone.now)),
                ('validade', models.DateField()),
                ('estado', models.CharField(choices=[('T', 'Tratada'), ('ET', 'Em tratamento'), ('R', 'Receitada')], max_length=2)),
                ('quant1', models.IntegerField(default=1)),
                ('desc1', models.CharField(blank='True', max_length=100)),
                ('quant2', models.IntegerField(blank='True', default='0')),
                ('desc2', models.CharField(blank='True', max_length=100)),
                ('quant3', models.IntegerField(blank='True', default='0')),
                ('desc3', models.CharField(blank='True', max_length=100)),
                ('quant4', models.IntegerField(blank='True', default='0')),
                ('desc4', models.CharField(blank='True', max_length=100)),
                ('quant5', models.IntegerField(blank='True', default='0')),
                ('desc5', models.CharField(blank='True', max_length=100)),
                ('id_medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_receitas.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('tel', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='id_utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_receitas.Utente'),
        ),
        migrations.AddField(
            model_name='receita',
            name='medicamento1',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='medA', to='sistema_receitas.Medicamento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='medicamento2',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='medB', to='sistema_receitas.Medicamento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='medicamento3',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='medC', to='sistema_receitas.Medicamento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='medicamento4',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='medD', to='sistema_receitas.Medicamento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='medicamento5',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='medE', to='sistema_receitas.Medicamento'),
        ),
    ]
